### ISSUE TITLE
dayOfTheWeek() has incorrect range

### ISSUE THREAD

**Issue by Levent-Keskin** [SV-Zanshin/DS3231M#22]
## Expected Behavior

dayOfTheWeek() is not in the range { 1 to 7 } as declared. 

## Actual Behavior

dayOfTheWeek() is in the range { 0 to 6 }

It will not be a problem if the range is declared as { 0 to 6 } in the Library.

**Comment by SV-Zanshin** [comment]
I've corrected the library so that the range is returned as 1-7 as opposed to 0-6

**Comment by SV-Zanshin** [comment]
Created a new release of 1.0.9
