### ISSUE TITLE
Calculate leap year

### ISSUE THREAD

**Issue by capitainekurck** [SV-Zanshin/DS3231M#23]
Hello,

I m not a C guru but it seem that to find a leap year you divide the year by 4. you must also consider dividing by 100 and 400.
There is an explanation here:
[https://learn.microsoft.com/en-us/office/troubleshoot/excel/determine-a-leap-year](url)
or here but it mid french mid english
[https://fr.wikihow.com/calculer-les-ann%C3%A9es-bissextiles](url)
regard

**Comment by SV-Zanshin** [comment]
That is correct, the original formula was incomplete, it has now been fixed to read

if (m > 2 && (((y % 4 == 0) && (y % 100 != 0)) || (y % 400 == 0)))

**Comment by SV-Zanshin** [comment]
Change implemented in source

**Comment by SV-Zanshin** [comment]
Fixed
