### ISSUE TITLE
logic on pinAlarm and pinSquareWave are inverted

### ISSUE THREAD

**Issue by lagg070988** [SV-Zanshin/DS3231M#9]
`void DS3231M_Class::pinAlarm() { 
  writeByte(DS3231M_CONTROL,readByte(DS3231M_CONTROL)&~0x4);  // Set bit 3 to on       
} // of method pinAlarm()`
this logical operator (&~) should be an **or** |

`void DS3231M_Class::pinSquareWave()
{
  writeByte(DS3231M_CONTROL,readByte(DS3231M_CONTROL)|0x4);
} // of method pinSquareWave()`
this logical operator (|) should be an **and**  &~

**Comment by SV-Zanshin** [comment]
Sorry for the delay - I am currently travelling. I'll update the library in the coming week.

**Comment by SV-Zanshin** [comment]
Sorry it took so long. I'm back home now and have updated the library code.
